import{a as v,S as E,i as a}from"./assets/vendor-CrlV4O_2.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))s(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const i of o.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&s(i)}).observe(document,{childList:!0,subtree:!0});function n(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function s(e){if(e.ep)return;e.ep=!0;const o=n(e);fetch(e.href,o)}})();const q="50845071-46be9009d91c767b22c84ce04",P="https://pixabay.com/api/",B=15;async function m(r,t=1){const n=await v.get(P,{params:{key:q,q:r,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:B,page:t}});return{images:n.data.hits,total:n.data.totalHits}}const f=document.querySelector(".gallery"),p=document.querySelector(".loader"),y=document.querySelector(".load-more"),M=new E(".gallery a",{captionsData:"alt",captionPosition:"bottom",captionDelay:250,overlayOpacity:.3});function g(r){const t=r.map(({webformatURL:n,largeImageURL:s,tags:e,likes:o,views:i,comments:S,downloads:w})=>`
      <li class="gallery-item">
        <a href="${s}">
          <img src="${n}" alt="${e}" />
        </a>
        <div class="gallery-info">
          <p><b>Likes</b> ${o}</p>
          <p><b>Views</b> ${i}</p>
          <p><b>Comments</b> ${S}</p>
          <p><b>Downloads</b> ${w}</p>
        </div>
      </li>`).join("");f.insertAdjacentHTML("beforeend",t),M.refresh()}function R(){f.innerHTML=""}function d(){y.classList.add("hidden")}function h(){y.classList.remove("hidden")}function L(){p.classList.remove("hidden")}function b(){p.classList.add("hidden")}const $=document.querySelector(".form"),O=document.querySelector('input[name="search-text"]'),A=document.querySelector(".load-more");let l="",c=1,u=0;$.addEventListener("submit",x);A.addEventListener("click",H);async function x(r){if(r.preventDefault(),l=O.value.trim(),c=1,!l){a.error({title:"Error",message:"Please enter a search query.",position:"topRight"});return}L(),d(),R();try{const{images:t,total:n}=await m(l,c);if(u=n,t.length===0){a.warning({title:"No Results",message:"No images match your search. Try again!",position:"center"});return}g(t),t.length<u&&h()}catch{a.error({title:"Error",message:"Something went wrong. Please try again later.",position:"topRight"})}finally{b()}}async function H(){c+=1,L(),d();try{const{images:r}=await m(l,c);g(r),N(),document.querySelectorAll(".gallery-item").length>=u?(a.info({title:"End of Results",message:"We're sorry, but you've reached the end of search results.",position:"center"}),d()):h()}catch{a.error({title:"Error",message:"Failed to load more images.",position:"topRight"})}finally{b()}}function N(){const{height:r}=document.querySelector(".gallery").firstElementChild.getBoundingClientRect();window.scrollBy({top:r*2,behavior:"smooth"})}
//# sourceMappingURL=index.js.map
